const cars = [
  {driver:'Martini', type:'BYD', seats:7, people:['Martini','Elona','Eljon','Sejla','Elona Q','Laura','Nevila']},
  {driver:'Ylli', type:'Nissan Qashqai', seats:5, people:['Ylli','Arta','Joel','Endri','Dojna']},
  {driver:'Mario', type:'Ford', seats:5, people:['Mario','Rexhina','Erla','Albora','Helio']},
  {driver:'Niku', type:'Ford', seats:5, people:['Niku','Gelsi','Asiel','Jola','Leonard']},
  {driver:'Landi', type:'Golf', seats:5, people:['Denisa','Dea','Elda','Bertina','Landi']},
  {driver:'Simoni', type:'Hyundai', seats:5, people:['Simoni','Lori','Solen','Luka']}
];

const accommodation = {
  merkure:{'Shtëpiza':['Erla','Rexhina','Elona Q','Albora'],'Çadra 1':['Leonard','Helio'],'Çadra 2':['Ylli','Arta'],'Çadra 3':['Niku','Gelsi'],'Çadra 4':['Asiel','Joel'],'Çadra 5':['Nevila','Laura'],'Çadra 6':['Martin','Elona'],'Çadra 7':['Eljon','Sejla'],'Çadra 8':['Endri','Mario']},
  enjte:{'Shtëpiza':['Erla','Rexhina','Elona Q','Bertina'],'Çadra 1':['Albora','Helio'],'Çadra 2':['Ylli','Arta'],'Çadra 3':['Niku','Gelsi'],'Çadra 4':['Asiel','Joel'],'Çadra 5':['Nevila','Laura','Elda'],'Çadra 6':['Martin','Elona'],'Çadra 7':['Eljon','Sejla'],'Çadra 8':['Endri','Mario'],'Çadra 9':['Leonard','Landi'],'Çadra 10':['Denisa','Dea']},
  premte:{'Shtëpiza':['Erla','Dojna','Jola','Bertina'],'Çadra 1':['Albora','Helio'],'Çadra 2':['Ylli','Arta'],'Çadra 3':['Niku','Gelsi'],'Çadra 4':['Asiel','Joel'],'Çadra 5':['Nevila','Laura','Elda'],'Çadra 6':['Martin','Elona'],'Çadra 7':['Eljon','Sejla'],'Çadra 8':['Endri','Mario'],'Çadra 9':['Leonard','Landi'],'Çadra 10':['Denisa','Dea'],'Çadra 11':['Rexhina','Elona Q']},
  shtune:{'Shtëpiza':['Erla','Dojna','Jola','Bertina'],'Çadra 1':['Albora','Helio'],'Çadra 2':['Ylli','Arta'],'Çadra 3':['Niku','Gelsi'],'Çadra 4':['Asiel','Joel'],'Çadra 5':['Nevila','Laura','Elda'],'Çadra 6':['Martin','Elona'],'Çadra 7':['Eljon','Sejla'],'Çadra 8':['Endri','Mario'],'Çadra 9':['Leonard','Landi'],'Çadra 10':['Denisa','Dea'],'Çadra 11':['Rexhina','Elona Q']}
};

const days = {
  merkure:{date:'E Mërkurë • 15 Qershor',title:'Upgrade i Mendjes',theme:'Mos jetoni me mendësinë e vjetër.',verse:'Romakëve 12:2',keyword:'Ripërtëritja e mendjes',schedule:[['05:00','Nisja nga Tirana','🚌'],['06:30','Mëngjes te Zdrava','🥐'],['07:30','Selfie në Vlorë Bypass','📸'],['09:00','Mbërritja te çadrat dhe akomodimi','⛺'],['10:00','Plazh për të gjithë dhe lojëra','🏖️'],['13:00','Dreka','🍽️'],['14:00','Vazhdim plazhi, njohje dhe lojëra','🤝'],['18:00','Dush dhe përgatitje për darkën','🚿'],['19:00','Darka','🍲'],['20:00','Shërbesa e parë','🎤'],['21:30','Kafe dhe pjesa e dytë e ndeshjes në Jalë','☕'],['00:00','Gjumë','🌙']],services:['mendja']},
  enjte:{date:'E Enjte • 16 Qershor',title:'Falje dhe Dashuri',theme:'Falja të çliron; dashuria transformon.',verse:'Efesianëve 4:31–32 • 1 Korintasve 13',keyword:'Falje dhe dashuri',schedule:[['08:00','Zgjimi','☀️'],['09:00','Mëngjesi','🥐'],['09:30','Nisja për në Shpellën e Pëllumbasit','🥾'],['10:00','Shërbesa e dytë në Shpellën e Pëllumbasit','🎤'],['11:30','Plazh në Pëllumbas','🏖️'],['13:00','Kthim për drekë','🍽️'],['14:00','Plazh, lojëra dhe njohje','🤝'],['18:00','Dush','🚿'],['19:00','Darka','🍲'],['20:00','Shërbesa e tretë','🎤'],['22:00','Shëtitje në Himarë','🌃'],['00:00','Kthim dhe gjumë','🌙']],services:['falja','dashuria']},
  premte:{date:'E Premte • 17 Qershor',title:'Fjalët dhe Besimi',theme:'Fjalët ndërtojnë; besimi na çon përpara.',verse:'Jakobi 3 • Hebrenjve 11',keyword:'Fjalë që japin jetë dhe hapa besimi',schedule:[['08:00','Zgjimi','☀️'],['09:00','Mëngjesi','🥐'],['09:30','Nisja për në Gjipe; gjatë udhëtimit zhvillohet shërbesa e katërt','🥾'],['13:00','Drekë, plazh dhe lojëra','🏖️'],['17:00','Kthim në kamp','⛺'],['18:00','Dush','🚿'],['19:00','Darka','🍲'],['20:00','Shërbesa e pestë','🎤'],['22:00','Shëtitje në Dhërmi','🌃'],['00:00','Kthim dhe gjumë','🌙']],services:['fjalet','besimi']},
  shtune:{date:'E Shtunë • 18 Qershor',title:'Disiplina dhe Misioni',theme:'Versioni i ri kërkon zakone të reja dhe një jetë me mision.',verse:'1 Timoteut 4:7–8 • Mateu 28',keyword:'Disiplinë dhe mision',schedule:[['08:00','Zgjimi','☀️'],['09:00','Mëngjesi','🥐'],['09:30','Nisja për në Plazhin e Akuariumit','🥾'],['10:00','Shërbesa e gjashtë','🎤'],['12:30','Kthim në kamp','⛺'],['13:00','Dreka','🍽️'],['14:00','Plazh dhe lojëra','🏖️'],['18:00','Dush','🚿'],['19:00','Darka','🍲'],['20:00','Shërbesa e shtatë','🎤'],['22:00','Kafe në Jalë','☕'],['00:00','Gjumë','🌙']],services:['disiplina','misioni']},
  diele:{date:'E Diel • 19 Qershor',title:'Dorëzim i Plotë',theme:'Upgrade nuk është më shumë informacion, por më shumë transformim.',verse:'Romakëve 12:1',keyword:'Dorëzim i plotë',schedule:[['08:00','Zgjimi','☀️'],['09:00','Mëngjesi','🥐'],['09:30','Nisja për në Përmet','🚌'],['11:30','Kafe në Grykën e Këlcyrës','☕'],['13:30','Drekë te Trifilia në Përmet','🍽️'],['15:30','Llixhat e Bënjës','♨️'],['17:30','Nisja për në Fier','🚌'],['19:30','Kafe te Liqeni i Hozit','☕'],['20:30','Ndalim në Fier për darkë dhe për të parë finalen e Botërorit','⚽'],['23:00','Nisja për në Tiranë','🚌'],['00:30','Mbërritja në Tiranë','🏠']],services:['dorezimi']}
};

const services = {
  mendja:{title:'Shërbesa 1 — Upgrade i Mendjes',password:'mendja',text:'Romakëve 12:2',intro:'Mos jetoni me mendësinë e vjetër.',points:['Çdo ndryshim fillon në mendje.','Nuk mund të jetosh një jetë të re me një mendësi të vjetër.','Besimtari duhet të mendojë ndryshe nga bota.','Çfarë duhet të çinstalojmë nga mendja?','Çfarë duhet të instalojmë sipas Fjalës?'],verses:['Filipianëve 4:8','Efesianëve 4:23','2 Korintasve 10:5']},
  falja:{title:'Shërbesa 2 — Upgrade në Falje',password:'falja',text:'Efesianëve 4:31–32',intro:'Falja nuk është emocion; është vendim.',points:['Falja nuk e justifikon gabimin.','Falja të çliron ty.','Zemra që nuk fal nuk mund të rritet.','Jezusi është modeli ynë.'],verses:['Mateu 18','Kolosianëve 3:13','Luka 23:34']},
  dashuria:{title:'Shërbesa 3 — Upgrade në Dashuri',password:'dashuria',text:'1 Korintasve 13',intro:'Dashuri që duron, fal dhe sakrifikon.',points:['Nuk mban llogari të së keqes.','Nuk kërkon interesin e vet.','Dashuria e Krishtit shihet në veprime.','A është dashuria ime ende versioni i vjetër?'],verses:['Gjoni 13:35','1 Gjonit 4']},
  fjalet:{title:'Shërbesa 4 — Upgrade në Fjalët e tua',password:'fjalet',text:'Jakobi 3',intro:'Gjuha ndërton ose shkatërron.',points:['Fjalët zbulojnë zemrën.','Bekimi dhe mallkimi nuk duhet të dalin nga e njëjta gojë.','Besimtari duhet të flasë jetë.'],verses:['Efesianëve 4:29','Fjalët e Urta 18:21','Mateu 12:34']},
  besimi:{title:'Shërbesa 5 — Upgrade në Besim',password:'besimi',text:'Hebrenjve 11',intro:'Perëndia kërkon hapa besimi.',points:['Mos jetoni vetëm nga logjika.','Frika mban versionin e vjetër.','Besimi sjell versionin e ri.'],verses:['2 Korintasve 5:7','Mateu 14']},
  disiplina:{title:'Shërbesa 6 — Upgrade në Disiplinë',password:'disiplina',text:'1 Timoteut 4:7–8',intro:'Versioni i ri kërkon zakone të reja.',points:['Disiplina është frymore.','Menaxho kohën, financat dhe trupin.','Kultivo leximin, lutjen dhe shërbesën.'],verses:['Fjalët e Urta 6','Galatasve 6:9','1 Korintasve 9:24–27']},
  misioni:{title:'Shërbesa 7 — Upgrade në Mision',password:'misioni',text:'Mateu 28',intro:'Besimi nuk është vetëm për veten.',points:['Kush po ndryshon për shkakun tim?','Kujt po i flas për Krishtin?','A jam konsumator apo ndërtues?'],verses:['Veprat 1:8','Isaia 6','Romakëve 10']},
  dorezimi:{title:'Shërbesa 8 — Upgrade në Dorëzim të Plotë',password:'dorezimi',text:'Romakëve 12:1',intro:'Kulmi i kampit: më shumë transformim.',points:['Dorëzim i plotë.','Lënia e versionit të vjetër.','Marrja e identitetit të ri.','Jetesa për Krishtin.'],verses:['Galatasve 2:20','Filipianëve 3','Luka 9:23']}
};

const dayOrder=['merkure','enjte','premte','shtune','diele'];
const dayLabels={merkure:'E Mërkurë',enjte:'E Enjte',premte:'E Premte',shtune:'E Shtunë',diele:'E Diel'};
let currentDay='merkure', pendingService=null;
const unlocked=new Set(JSON.parse(localStorage.getItem('upgradeUnlocked')||'[]'));

function renderNav(){const nav=document.getElementById('mainNav');nav.innerHTML=`<button class="nav-button active" data-view="details"><span class="nav-icon">⌂</span><span><strong>Detajet</strong><small>Transporti dhe akomodimi</small></span><b>→</b></button>`+dayOrder.map((d,i)=>`<button class="nav-button" data-view="${d}"><span class="nav-date">${15+i}</span><span><strong>${dayLabels[d]}</strong><small>${days[d].title}</small></span><b>→</b></button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>openView(b.dataset.view));}
function openView(view){document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('detailsView').classList.toggle('active',view==='details');document.getElementById('dayView').classList.toggle('active',view!=='details');document.getElementById('pageTitle').textContent=view==='details'?'Detajet e organizimit':dayLabels[view];if(view!=='details'){currentDay=view;renderDay();}closeSidebar();window.scrollTo({top:0,behavior:'smooth'});}
function renderCars(filter=''){const term=filter.toLowerCase();document.getElementById('carGrid').innerHTML=cars.filter(c=>(c.driver+c.type+c.people.join(' ')).toLowerCase().includes(term)).map(c=>`<article class="car-card"><div class="car-head"><span>🚙</span><div><h4>${c.driver}</h4><p>${c.type}</p></div><b>${c.people.length}/${c.seats}</b></div><ul>${c.people.map((p,i)=>`<li><span>${i===0?'🧑‍✈️':'👤'}</span>${p}</li>`).join('')}</ul></article>`).join('');}
function renderAccommodation(day='merkure',filter=''){document.querySelectorAll('.day-tab').forEach(b=>b.classList.toggle('active',b.dataset.day===day));const term=filter.toLowerCase();const data=accommodation[day]||{};document.getElementById('accommodationGrid').innerHTML=Object.entries(data).filter(([u,p])=>(u+p.join(' ')).toLowerCase().includes(term)).map(([u,p])=>`<article class="unit-card"><div><span>${u==='Shtëpiza'?'🏠':'⛺'}</span><h4>${u}</h4></div><ul>${p.map(x=>`<li>👤 ${x}</li>`).join('')}</ul></article>`).join('');}
function setupAccommodation(){const tabs=document.getElementById('accommodationTabs');tabs.innerHTML=['merkure','enjte','premte','shtune'].map(d=>`<button class="day-tab ${d==='merkure'?'active':''}" data-day="${d}">${dayLabels[d]}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{tabs.dataset.active=b.dataset.day;renderAccommodation(b.dataset.day,document.getElementById('accommodationSearch').value);});tabs.dataset.active='merkure';}
function renderDay(){const d=days[currentDay];dayDate.textContent=d.date;dayTitle.textContent=d.title;dayTheme.textContent=d.theme;dayVerse.textContent=d.verse;dayKeyword.textContent=d.keyword;scheduleTitle.textContent=dayLabels[currentDay];scheduleList.innerHTML=d.schedule.map(([t,a,icon])=>`<div class="timeline-item"><div class="time">${t}</div><div class="dot"></div><div class="activity"><span>${icon}</span><p>${a}</p></div></div>`).join('');servicesList.innerHTML=d.services.map(id=>renderService(id)).join('');personalNotes.value=localStorage.getItem(`notes-${currentDay}`)||'';}
function renderService(id){const s=services[id], isOpen=unlocked.has(id);return `<article class="service-card ${isOpen?'unlocked':''}" data-service="${id}"><div class="service-header"><div><span class="section-kicker">${s.text}</span><h3>${s.title}</h3><p>${s.intro}</p></div>${isOpen?'<span class="status-open">Hapur ✓</span>':`<button class="unlock-button" onclick="askPassword('${id}')">🔐 Hape</button>`}</div>${isOpen?`<div class="service-content"><div class="content-block"><h4>📖 Predikimi</h4><ul>${s.points.map(p=>`<li>${p}</li>`).join('')}</ul></div><div class="content-block"><h4>🔖 Vargje shtesë</h4><div class="verse-tags">${s.verses.map(v=>`<span>${v}</span>`).join('')}</div></div><div class="service-tools"><div><h4>💬 Pyetje</h4><textarea placeholder="Shto pyetjet e diskutimit…"></textarea></div><div><h4>🎲 Lojë interaktive</h4><textarea placeholder="Përshkruaj lojën…"></textarea></div><div><h4>🔥 Sfida</h4><textarea placeholder="Shkruaj sfidën e shërbesës…"></textarea></div><div><h4>🎵 Këngë adhurimi</h4><textarea placeholder="Shto këngët…"></textarea></div></div></div>`:''}</article>`;}
window.askPassword=id=>{pendingService=id;modalTitle.textContent=services[id].title;passwordInput.value='';passwordError.textContent='';passwordModal.hidden=false;setTimeout(()=>passwordInput.focus(),50);};
passwordForm.onsubmit=e=>{e.preventDefault();if(passwordInput.value.trim().toLowerCase()===services[pendingService].password){unlocked.add(pendingService);localStorage.setItem('upgradeUnlocked',JSON.stringify([...unlocked]));passwordModal.hidden=true;renderDay();showToast('Shërbesa u hap me sukses.');}else passwordError.textContent='Password i pasaktë.';};
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);}
function closeSidebar(){sidebar.classList.remove('open');sidebarBackdrop.classList.remove('show');}
menuButton.onclick=()=>{sidebar.classList.add('open');sidebarBackdrop.classList.add('show');};sidebarBackdrop.onclick=closeSidebar;closeModal.onclick=()=>passwordModal.hidden=true;passwordModal.onclick=e=>{if(e.target===passwordModal)passwordModal.hidden=true;};togglePassword.onclick=()=>passwordInput.type=passwordInput.type==='password'?'text':'password';
lockAll.onclick=()=>{unlocked.clear();localStorage.removeItem('upgradeUnlocked');if(document.getElementById('dayView').classList.contains('active'))renderDay();showToast('Të gjitha shërbesat u bllokuan.');};
personalNotes.oninput=()=>localStorage.setItem(`notes-${currentDay}`,personalNotes.value);
carSearch.oninput=e=>renderCars(e.target.value);accommodationSearch.oninput=e=>renderAccommodation(accommodationTabs.dataset.active||'merkure',e.target.value);
renderNav();renderCars();setupAccommodation();renderAccommodation();
